import { execFile } from "node:child_process";
import fsp from "node:fs/promises";
import path from "node:path";
import { promisify } from "node:util";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import { makeProject, writeRel, linkRel } from "./helpers.js";

const run = promisify(execFile);
const here = path.dirname(fileURLToPath(import.meta.url));
const CLI = path.resolve(here, "../dist/cli.js");
const ESC = String.fromCharCode(27);
const stripAnsi = (s: string): string => s.replace(new RegExp(`${ESC}\\[[0-9;?]*[a-zA-Z]`, "g"), "");
const hasDist = await fsp
  .access(CLI)
  .then(() => true)
  .catch(() => false);

describe.skipIf(!hasDist)("cli smoke", () => {
  it("prints help and version", async () => {
    const help = await run("node", [CLI, "--help"]);
    expect(help.stdout).toContain("Usage:");
    const ver = await run("node", [CLI, "--version"]);
    expect(ver.stdout.trim()).toMatch(/^agents-aliases \d+\.\d+\.\d+$/);
  });

  it("rejects unknown commands with exit code 2", async () => {
    await expect(run("node", [CLI, "bogus"])).rejects.toMatchObject({ code: 2 });
  });

  it("rejects unknown flags with exit code 2", async () => {
    const err = await run("node", [CLI, "--dri-run"], { cwd: process.cwd() }).catch(
      (e) => e as Error & { stderr: string },
    );
    expect(err.stderr).toContain("Invalid arguments");
  });

  it("rejects unknown --agents ids with exit code 2", async () => {
    const root = await makeProject();
    await writeRel(root, "AGENTS.md", "# agents\n");
    const err = await run("node", [CLI, "--yes", "--agents", "bogus"], { cwd: root }).catch(
      (e) => e as Error & { stderr: string },
    );
    expect(err.stderr).toContain("unknown agent id(s): bogus");
  });

  it("wires everything non-interactively with --yes", async () => {
    const root = await makeProject();
    await writeRel(root, "AGENTS.md", "# agents\nrules here\n");
    const res = await run("node", [CLI], { cwd: root });
    const out = stripAnsi(res.stdout);
    expect(out).toContain("CLAUDE.md -> AGENTS.md");
    expect(out).toContain("copilot-instructions.md -> ../AGENTS.md");

    const claude = await fsp.readlink(path.join(root, "CLAUDE.md"));
    expect(claude).toBe("AGENTS.md");

    const check = await run("node", [CLI, "check"], { cwd: root });
    expect(check.stdout).toContain("all agent aliases are wired correctly");
  });

  it("dry run leaves the filesystem untouched", async () => {
    const root = await makeProject();
    await writeRel(root, "AGENTS.md", "# agents\n");
    await run("node", [CLI, "--yes", "--dry-run"], { cwd: root });
    await expect(fsp.access(path.join(root, "CLAUDE.md"))).rejects.toThrow();
  });

  it("check fails on broken aliases and duplicates", async () => {
    const root = await makeProject();
    await writeRel(root, "AGENTS.md", "v1\n");
    await linkRel(root, "CLAUDE.md", "GEMINI.md");
    await expect(run("node", [CLI, "check"], { cwd: root })).rejects.toMatchObject({
      code: 1,
    });

    const root2 = await makeProject();
    await writeRel(root2, "AGENTS.md", "v1\n");
    await writeRel(root2, "CLAUDE.md", "v2 diverged\n");
    await expect(run("node", [CLI, "check"], { cwd: root2 })).rejects.toMatchObject({
      code: 1,
    });
  });

  it("sync relinks a broken alias to an existing canonical", async () => {
    const root = await makeProject();
    await writeRel(root, "AGENTS.md", "# agents\n");
    await writeRel(root, ".cursor/rules/review.mdc", "---\ndescription: R\n---\nbody\n");
    await writeRel(
      root,
      ".windsurf/rules/review.md",
      `---\ntrigger: glob\ndescription: Review\n---\n<!-- GENERATED by agents-aliases. Source: .cursor/rules/review.mdc. DO NOT EDIT. -->\n\nSTALE BODY.\n`,
    );
    await linkRel(root, "CLAUDE.md", "deleted-target.md");

    const res = await run("node", [CLI, "sync"], { cwd: root });
    expect(res.stdout).toContain("1 link(s) repaired");

    const fsp2 = await import("node:fs/promises");
    expect(await fsp2.readlink(path.join(root, "CLAUDE.md"))).toBe("AGENTS.md");
    const refreshed = await fsp2.readFile(path.join(root, ".windsurf/rules/review.md"), "utf8");
    expect(refreshed).toContain("body");
  });

  it("reports unfixable broken links when no canonical exists", async () => {
    const root = await makeProject();
    await linkRel(root, "GEMINI.md", "nowhere-forever.md");

    const err = await run("node", [CLI, "sync"], { cwd: root }).catch((e) => e as Error & { stdout: string });
    expect(err.stdout).toContain("no canonical to relink to");
  });
});
