import { describe, expect, it } from "vitest";

import { detect } from "../src/detect.js";
import { linkRel, makeProject, writeRel } from "./helpers.js";

describe("detect", () => {
  it("classifies real files, symlinks, broken links and missing paths", async () => {
    const root = await makeProject();
    await writeRel(root, "AGENTS.md", "# agents\n");
    await writeRel(root, "CLAUDE.md", "# agents\n");
    await linkRel(root, ".github/copilot-instructions.md", "../AGENTS.md");
    await linkRel(root, "GEMINI.md", "void.md");

    const d = await detect(root);
    const ins = d.concerns.instructions;

    expect([...ins.sources]).toEqual(["codex", "claude"]);
    expect(ins.links).toContain("copilot");
    expect(ins.brokenLinks).toContain("gemini");

    expect(d.fileHashes.get("AGENTS.md")).toBe(d.fileHashes.get("CLAUDE.md"));

    const copilotState = ins.states.get("copilot")!;
    expect(copilotState.linkText).toBe("../AGENTS.md");
  });

  it("signatures skill directories and lists rule files with generated markers", async () => {
    const root = await makeProject();
    await writeRel(root, ".agents/skills/alpha/SKILL.md", "skill alpha\n");
    await writeRel(root, ".claude/skills/alpha/SKILL.md", "skill alpha\n");
    await writeRel(root, ".cursor/rules/review.mdc", "---\ndescription: x\n---\nbody\n");
    await writeRel(
      root,
      ".windsurf/rules/review.md",
      `---\ntrigger: glob\n---\n<!-- GENERATED by agents-aliases. Source: .cursor/rules/review.mdc. DO NOT EDIT. -->\n\nbody\n`,
    );

    const d = await detect(root);
    expect(d.dirSignatures.get(".agents/skills")).toBe(d.dirSignatures.get(".claude/skills"));
    expect(d.generatedFiles).toEqual([
      {
        dirPresetId: "rules-windsurf",
        fileName: "review.md",
        sourceRelPath: ".cursor/rules/review.mdc",
      },
    ]);
  });

  it("reports non-git projects without dirty paths", async () => {
    const root = await makeProject();
    const d = await detect(root);
    expect(d.isGitRepo).toBe(false);
    expect(d.dirtyPaths.size).toBe(0);
  });
});
