import path from "node:path";

import type { AdapterFormat } from "../presets.js";

export interface FrontmatterSplit {
  frontmatter: Record<string, string>;
  body: string;
}

export function splitFrontmatter(content: string): FrontmatterSplit {
  const normalized = content.replace(/\r\n/g, "\n");
  if (!normalized.startsWith("---\n")) {
    return { frontmatter: {}, body: normalized };
  }
  const rest = normalized.slice(4);
  const end = rest.indexOf("\n---");
  if (end === -1) {
    return { frontmatter: {}, body: normalized };
  }
  const block = rest.slice(0, end);
  const body = rest.slice(end + 4).replace(/^\n+/, "");
  const frontmatter: Record<string, string> = {};
  for (const line of block.split("\n")) {
    const idx = line.indexOf(":");
    if (idx === -1) continue;
    const key = line.slice(0, idx).trim();
    let value = line.slice(idx + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    if (key) frontmatter[key] = value;
  }
  return { frontmatter, body };
}

function quoteYaml(value: string): string {
  if (/^[A-Za-z0-9_*.,{}/[\]"\s-]+$/.test(value)) {
    return value;
  }
  return JSON.stringify(value);
}

export function serializeFrontmatter(frontmatter: Record<string, string>): string {
  const lines = Object.entries(frontmatter).map(([k, v]) => `${k}: ${quoteYaml(v)}`);
  return lines.length ? `---\n${lines.join("\n")}\n---\n` : "";
}

export const MARKER_PREFIX = "<!-- GENERATED by agents-aliases. Source: ";
export const MARKER_SUFFIX = ". DO NOT EDIT. -->";

export function makeMarker(sourceRelPath: string): string {
  return `${MARKER_PREFIX}${sourceRelPath}${MARKER_SUFFIX}`;
}

export function parseGeneratedSource(content: string): string | null {
  const normalized = content.replace(/\r\n/g, "\n");
  if (!normalized.includes(MARKER_PREFIX)) return null;
  for (const line of normalized.split("\n")) {
    const trimmed = line.trim();
    if (trimmed.startsWith(MARKER_PREFIX) && trimmed.endsWith(MARKER_SUFFIX)) {
      return trimmed.slice(MARKER_PREFIX.length, -MARKER_SUFFIX.length);
    }
  }
  return null;
}

function firstHeading(body: string): string | undefined {
  for (const line of body.split("\n")) {
    const m = /^#\s+(.+)$/.exec(line.trim());
    if (m?.[1] !== undefined) return m[1].trim().replace(/`/g, "");
  }
  return undefined;
}

const RULE_EXT_PATTERN = /\.(mdc|instructions\.md|md)$/;

export function stripRuleExtension(fileName: string): string {
  return fileName.replace(RULE_EXT_PATTERN, "");
}

export function targetFileName(canonicalFileName: string, format: AdapterFormat): string {
  const base = stripRuleExtension(canonicalFileName);
  switch (format) {
    case "claude":
      return `${base}.md`;
    case "mdc":
      return `${base}.mdc`;
    case "copilot-instructions":
      return `${base}.instructions.md`;
    case "windsurf":
      return `${base}.md`;
  }
}

export interface GenerateAdapterInput {
  sourceRelPath: string;
  sourceContent: string;
  format: AdapterFormat;
}

export function generateAdapter(input: GenerateAdapterInput): string {
  const { sourceRelPath, sourceContent, format } = input;
  const { frontmatter, body } = splitFrontmatter(sourceContent);

  const description =
    frontmatter.description ?? firstHeading(body) ?? path.basename(stripRuleExtension(sourceRelPath));
  const globs = frontmatter.globs ?? frontmatter.applyTo ?? frontmatter.paths;

  let fm: Record<string, string>;
  switch (format) {
    case "claude": {
      fm = {};
      const paths = frontmatter.paths ?? globs;
      if (paths) {
        fm.paths = paths.startsWith("[") ? paths : `["${paths}"]`;
      }
      break;
    }
    case "mdc": {
      fm = { description };
      const alwaysApply = frontmatter.alwaysApply ?? (globs ? "false" : "true");
      if (globs) fm.globs = globs;
      fm.alwaysApply = alwaysApply;
      break;
    }
    case "copilot-instructions": {
      fm = {};
      if (frontmatter.applyTo || globs) fm.applyTo = frontmatter.applyTo ?? globs!;
      else fm.applyTo = "**";
      if (frontmatter.description && frontmatter.description !== description) {
        fm.description = frontmatter.description;
      }
      break;
    }
    case "windsurf": {
      fm = {};
      if (globs) {
        fm.trigger = frontmatter.trigger ?? "glob";
        fm.glob = globs;
      } else {
        fm.trigger = frontmatter.trigger ?? "always_on";
      }
      fm.description = description;
      break;
    }
  }

  const markerLine = makeMarker(sourceRelPath);
  const cleanBody = body.replace(/^\n+/, "").replace(/\n*$/, "\n");
  return `${serializeFrontmatter(fm)}${markerLine}\n\n${cleanBody}`;
}
